import {
  Bot,
  CarFront,
  Code2,
  Cuboid,
  Cpu,
  Gamepad2,
  Monitor,
  Palette,
  Printer,
  Smartphone,
  Sparkles,
  Trophy,
  Users,
  UtensilsCrossed,
  Video,
  SunMedium,
} from 'lucide-react';
import type {
  Amenity,
  MembershipDay,
  MembershipDayKey,
  MembershipSlot,
  MembershipSlotKey,
  Program,
} from './types';

export const membershipDays: MembershipDay[] = [
  { key: 'monday', label: 'Monday', labelBs: 'Ponedjeljak', shortLabel: 'MON', shortLabelBs: 'PON', summary: 'Fresh start', summaryBs: 'Novi start' },
  { key: 'tuesday', label: 'Tuesday', labelBs: 'Utorak', shortLabel: 'TUE', shortLabelBs: 'UTO', summary: 'Build mode', summaryBs: 'Build mode' },
  { key: 'wednesday', label: 'Wednesday', labelBs: 'Srijeda', shortLabel: 'WED', shortLabelBs: 'SRI', summary: 'Midweek focus', summaryBs: 'Sredina sedmice' },
  { key: 'thursday', label: 'Thursday', labelBs: 'Četvrtak', shortLabel: 'THU', shortLabelBs: 'ČET', summary: 'Creative flow', summaryBs: 'Kreativni flow' },
  { key: 'friday', label: 'Friday', labelBs: 'Petak', shortLabel: 'FRI', shortLabelBs: 'PET', summary: 'Launch energy', summaryBs: 'Launch energija' },
  { key: 'saturday', label: 'Saturday', labelBs: 'Subota', shortLabel: 'SAT', shortLabelBs: 'SUB', summary: 'Weekend lab', summaryBs: 'Vikend lab' },
  { key: 'sunday', label: 'Sunday', labelBs: 'Nedjelja', shortLabel: 'SUN', shortLabelBs: 'NED', summary: 'Closed', summaryBs: 'Zatvoreno', closed: true },
];

export const membershipSlots: MembershipSlot[] = [
  { key: 'slot1', label: '08:00 - 10:00' },
  { key: 'slot2', label: '10:00 - 12:00' },
  { key: 'slot3', label: '12:00 - 14:00' },
  { key: 'slot4', label: '14:00 - 16:00' },
];

export const slotOrder: Record<MembershipSlotKey, number> = {
  slot1: 0,
  slot2: 1,
  slot3: 2,
  slot4: 3,
};

export const createAvailability = (): Record<MembershipDayKey, Record<MembershipSlotKey, number>> => ({
  monday: { slot1: 9, slot2: 8, slot3: 7, slot4: 10 },
  tuesday: { slot1: 11, slot2: 6, slot3: 5, slot4: 9 },
  wednesday: { slot1: 7, slot2: 4, slot3: 6, slot4: 8 },
  thursday: { slot1: 10, slot2: 9, slot3: 6, slot4: 7 },
  friday: { slot1: 8, slot2: 5, slot3: 4, slot4: 6 },
  saturday: { slot1: 12, slot2: 10, slot3: 9, slot4: 11 },
  sunday: { slot1: 0, slot2: 0, slot3: 0, slot4: 0 },
});

export const amenities: Amenity[] = [
  {
    title: '15 AI Coding Stations + Chill Lounge',
    titleBs: '15 AI Coding Stanica + Chill Lounge',
    description: 'A 15-place AI-equipped coding zone paired with a chill lounge for breaks, gaming, and reset between work sessions.',
    descriptionBs: 'Zona sa 15 AI opremljenih coding mjesta i chill lounge dijelom za pauzu, gaming i reset između radnih sesija.',
    icon: Monitor,
  },
  {
    title: 'PlayStation 5',
    titleBs: 'PlayStation 5',
    description: 'Console zone for breaks, tournaments, and social hangouts between sessions.',
    descriptionBs: 'Konzola zona za pauze, turnire i druženje između sesija.',
    icon: Gamepad2,
  },
  {
    title: 'VR Corner',
    titleBs: 'VR Kutak',
    description: 'Immersive virtual reality experiences that make tech feel tangible and fun.',
    descriptionBs: 'VR iskustva koja čine tehnologiju opipljivom, modernom i zabavnom.',
    icon: Sparkles,
  },
  {
    title: 'Table Football',
    titleBs: 'Stoni Fudbal',
    description: 'Fast break energy for teams, rivals, and mid-session resets.',
    descriptionBs: 'Brza pauza za timove, rivale i reset između sesija.',
    icon: Trophy,
  },
  {
    title: '3D Printer + Free Filament',
    titleBs: '3D Printer + Besplatan Filament',
    description: 'Prototype ideas, parts, and school projects without extra material cost.',
    descriptionBs: 'Prototipi, dijelovi i školski projekti bez dodatnog troška materijala.',
    icon: Printer,
  },
  {
    title: 'Arduino + Robotics Kits',
    titleBs: 'Arduino + Robotika Kitovi',
    description: 'Hands-on electronics and robotics setup for sensors, movement, automation, and real prototype building.',
    descriptionBs: 'Praktična elektronika i robotika za senzore, kretanje, automatizaciju i izradu stvarnih prototipa.',
    icon: Cpu,
  },
  {
    title: 'Snacks',
    titleBs: 'Snack Zona',
    description: 'A casual fuel-up point to keep long creative blocks comfortable.',
    descriptionBs: 'Opuštena snack zona za lakše i udobnije kreativne blokove.',
    icon: UtensilsCrossed,
  },
  {
    title: 'Parking',
    titleBs: 'Parking',
    description: 'Reliable parking access for multiple vehicles, making drop-offs and longer stays easy.',
    descriptionBs: 'Stalan parking za više vozila, tako da su dolazak, ostanak i prevoz jednostavniji.',
    icon: CarFront,
  },
  {
    title: 'Rooftop Location',
    titleBs: 'Rooftop Lokacija',
    description: 'Set at the top of the building, with an open view, plenty of daylight, and a calm rooftop feel through the day.',
    descriptionBs: 'Smješten na vrhu zgrade, sa prelijepim pogledom, puno prirodnog svjetla i onim mirnim rooftop osjećajem kroz dan.',
    icon: SunMedium,
  },
];

const genericTutor: Program['tutor'] = {
  name: 'Techpark Team',
  title: 'Coming soon',
  titleBs: 'Uskoro',
  image: '/generic-tutor-avatar-flat.svg',
  link: null,
};

export const programs: Program[] = [
  {
    id: 'web-dev',
    title: 'Web Dev',
    titleBs: 'Web Dev',
    description: 'Learn how to plan, design, and build modern websites, landing pages, and interactive interfaces, from the first wireframe to a polished live version. The program focuses on structure, responsive layout, speed, usability, and the visual quality of the final product.',
    descriptionBs: 'Nauči kako planirati, dizajnirati i izraditi moderne web stranice, landing pageove i interaktivne interfejse, od prve skice do završene live verzije. Program stavlja fokus na strukturu, responsive layout, brzinu, UX i vizuelni kvalitet finalnog proizvoda.',
    schedule: 'Mon-Sat · Time coming soon',
    scheduleBs: 'Pon-Sub · Uskoro satnica',
    beginnerFocus: 'HTML, CSS, JavaScript, responsive thinking.',
    beginnerFocusBs: 'HTML, CSS, JavaScript i responsive razmišljanje.',
    advancedFocus: 'React, APIs, deployment, and product polish.',
    advancedFocusBs: 'React, API integracije, deployment i product polish.',
    enrolled: { beginner: 6, advanced: 4 },
    seats: 15,
    icon: Code2,
    tutor: {
      name: 'Nedim Kulašin',
      title: 'Software Engineer',
      titleBs: 'Software inžinjer',
      image: '/generic-tutor-avatar-flat.svg',
      link: 'https://ba.linkedin.com/in/nedim-kula%C5%A1in-64673911a',
    },
  },
  {
    id: '3d-modeling',
    title: '3D Modeling and 3D Print',
    titleBs: '3D Modeling and 3D Print',
    description: 'Move from digital object design to a real 3D printed result through hands-on work with shapes, dimensions, file preparation, and print-ready optimization. This program is built for students who want to combine creative thinking, technical precision, and a physical end product they can actually hold.',
    descriptionBs: 'Kroz ovaj program učiš kako digitalni model pretvoriti u stvarni 3D printani proizvod, kroz rad sa oblicima, mjerama, pripremom fajlova i optimizacijom za print. Program je namijenjen polaznicima koji žele spojiti kreativno razmišljanje, tehničku preciznost i konkretan krajnji rezultat koji mogu držati u ruci.',
    schedule: 'Tue-Sat · Time coming soon',
    scheduleBs: 'Uto-Sub · Uskoro satnica',
    beginnerFocus: 'Shapes, scale, printable models, and file preparation.',
    beginnerFocusBs: 'Oblici, skala, printable modeli i priprema fajlova.',
    advancedFocus: 'Functional parts, detailing, prototyping, and print optimization.',
    advancedFocusBs: 'Funkcionalni dijelovi, detalji, prototipi i optimizacija printa.',
    enrolled: { beginner: 5, advanced: 3 },
    seats: 15,
    icon: Cuboid,
    tutor: {
      name: 'Amer Viteškić',
      title: 'Mechanical Engineer',
      titleBs: 'Mašinski inženjer',
      image: 'https://media.licdn.com/dms/image/v2/D4E03AQFRNAVBRcN2Xw/profile-displayphoto-shrink_200_200/B4EZeNd3MrHIAY-/0/1750425106177?e=2147483647&v=beta&t=xDSvlbk4xe5TDUhquDO7ynnnbYj75fZIGgW9xclsZz8',
      link: 'https://ba.linkedin.com/in/amerviteskic?trk=people-guest_people_search-card',
    },
  },
  {
    id: 'app-dev',
    title: 'App Dev',
    titleBs: 'App Dev',
    description: 'Learn how an idea becomes a real mobile product through feature planning, user flow design, prototyping, and app-first product thinking. The focus is on mobile UX, practical logic, testing ideas early, and understanding how apps are shaped for real users.',
    descriptionBs: 'Nauči kako ideja postaje pravi mobilni proizvod kroz planiranje funkcionalnosti, dizajn korisničkog toka, prototip i app-first product razmišljanje. Fokus je na mobile UX-u, praktičnoj logici, ranom testiranju ideja i razumijevanju kako se aplikacije grade za stvarne korisnike.',
    schedule: 'Wed-Sat · Time coming soon',
    scheduleBs: 'Sri-Sub · Uskoro satnica',
    beginnerFocus: 'Mobile UX basics, app logic, prototyping, and publishing flow.',
    beginnerFocusBs: 'Osnove mobile UX-a, logika appova, prototip i publishing flow.',
    advancedFocus: 'React Native concepts, APIs, state, and app iteration.',
    advancedFocusBs: 'React Native koncepti, API-ji, state i iteracija aplikacije.',
    enrolled: { beginner: 6, advanced: 4 },
    seats: 15,
    icon: Smartphone,
    tutor: genericTutor,
  },
  {
    id: 'ui-ux',
    title: 'UI/UX Graphic Design',
    titleBs: 'UI/UX Graphic Design',
    description: 'Develop a strong eye for interfaces, layout, color, typography, and user flow so design becomes both attractive and functional. The program takes students from rough wireframes to polished visual systems and presentation-ready prototypes.',
    descriptionBs: 'Razvij osjećaj za interfejs, raspored, boje, tipografiju i korisničke tokove kako bi dizajn bio i privlačan i funkcionalan. Program vodi polaznike od početnih wireframea do dotjeranih vizuelnih sistema i prototipa spremnih za prezentaciju.',
    schedule: 'Thu-Sat · Time coming soon',
    scheduleBs: 'Čet-Sub · Uskoro satnica',
    beginnerFocus: 'Layout, typography, wireframes, and design habits.',
    beginnerFocusBs: 'Layout, tipografija, wireframe i dobre design navike.',
    advancedFocus: 'Design systems, product flows, and polished prototypes.',
    advancedFocusBs: 'Design sistemi, product flow i dotjerani prototipi.',
    enrolled: { beginner: 4, advanced: 3 },
    seats: 15,
    icon: Palette,
    tutor: genericTutor,
  },
  {
    id: 'ai-program',
    title: 'AI Program',
    titleBs: 'AI Program',
    description: 'Learn how AI tools actually work and how to use them for better productivity, creative work, research, and real-world output. The program covers prompting, safety, automation, and practical workflows that turn AI from a trend into a serious tool.',
    descriptionBs: 'Nauči kako AI alati stvarno rade i kako ih koristiti za veću produktivnost, kreativni rad, istraživanje i konkretan rezultat. Program pokriva prompting, sigurnost, automatizaciju i praktične workflowe koji AI pretvaraju iz trenda u ozbiljan alat.',
    schedule: 'Fri-Sat · Time coming soon',
    scheduleBs: 'Pet-Sub · Uskoro satnica',
    beginnerFocus: 'Prompting, AI safety, practical automation, and workflows.',
    beginnerFocusBs: 'Prompting, AI sigurnost, automacija i korisni workflowi.',
    advancedFocus: 'Model strategy, product ideas, and advanced creator pipelines.',
    advancedFocusBs: 'Strategija modela, product ideje i napredni creator pipelineovi.',
    enrolled: { beginner: 6, advanced: 5 },
    seats: 15,
    icon: Bot,
    tutor: genericTutor,
  },
  {
    id: 'arduino-robotics',
    title: 'Arduino and Robotics',
    titleBs: 'Arduino i Robotika',
    description: 'Enter the world of electronics, sensors, automation, and robotics through projects where ideas become devices that react, measure, light up, and move. The program combines hands-on building, logical thinking, and a clear understanding of how hardware and software work together.',
    descriptionBs: 'Uđi u svijet elektronike, senzora, automatizacije i robotike kroz projekte u kojima se ideje pretvaraju u uređaje koji reaguju, mjere, svijetle i kreću se. Program spaja praktičan rad, logičko razmišljanje i jasno razumijevanje kako hardware i software funkcionišu zajedno.',
    schedule: 'Mon-Sat · Time coming soon',
    scheduleBs: 'Pon-Sub · Uskoro satnica',
    beginnerFocus: 'Sensors, LEDs, circuits, Arduino basics, and simple robot movement.',
    beginnerFocusBs: 'Senzori, LED, strujna kola, Arduino osnove i jednostavno kretanje robota.',
    advancedFocus: 'Automation logic, multi-component builds, robotics control, and prototype integration.',
    advancedFocusBs: 'Automatizacija, složeniji sklopovi, upravljanje robotikom i integracija prototipa.',
    enrolled: { beginner: 5, advanced: 4 },
    seats: 15,
    icon: Cpu,
    tutor: genericTutor,
  },
  {
    id: 'game-dev',
    title: 'Game Dev',
    titleBs: 'Game Dev',
    description: 'Create your own game ideas, mechanics, worlds, and interactive experiences while learning how fun, challenge, and progression are designed. The program focuses on gameplay logic, level structure, feedback systems, and building playable concepts that feel intentional.',
    descriptionBs: 'Kreiraj vlastite game ideje, mehanike, svjetove i interaktivna iskustva dok učiš kako se dizajniraju zabava, izazov i progresija. Program je fokusiran na gameplay logiku, strukturu levela, feedback sisteme i izradu playable koncepata koji imaju jasan smisao.',
    schedule: 'Tue-Sat · Time coming soon',
    scheduleBs: 'Uto-Sub · Uskoro satnica',
    beginnerFocus: 'Game logic, level thinking, storytelling, and interaction basics.',
    beginnerFocusBs: 'Game logika, level thinking, storytelling i osnove interakcije.',
    advancedFocus: 'Production flow, systems, balancing, and playable demos.',
    advancedFocusBs: 'Production flow, sistemi, balans i playable demo verzije.',
    enrolled: { beginner: 6, advanced: 4 },
    seats: 15,
    icon: Gamepad2,
    tutor: genericTutor,
  },
  {
    id: 'roblox-game-dev',
    title: 'Roblox Game Dev',
    titleBs: 'Roblox Game Dev',
    description: 'Build Roblox worlds, gameplay loops, and scripted multiplayer experiences with a clear structure, progression, and polished flow. The program moves from Roblox Studio basics to scripting and systems that make a project feel more complete, engaging, and publish-ready.',
    descriptionBs: 'Pravi Roblox svjetove, gameplay loopove i scripted multiplayer iskustva sa jasnom strukturom, progresijom i dotjeranim flowom. Program vodi od osnova Roblox Studija do scriptanja i sistema koji projekat čine kompletnijim, zanimljivijim i spremnijim za objavu.',
    schedule: 'Wed-Sat · Time coming soon',
    scheduleBs: 'Sri-Sub · Uskoro satnica',
    beginnerFocus: 'Roblox Studio basics, level building, gameplay logic, and simple Lua scripting.',
    beginnerFocusBs: 'Roblox Studio osnove, gradnja levela, gameplay logika i jednostavni Lua skriptovi.',
    advancedFocus: 'Lua systems, multiplayer mechanics, progression loops, and polished publish-ready projects.',
    advancedFocusBs: 'Lua sistemi, multiplayer mehanike, progression loopovi i dotjerani publish-ready projekti.',
    enrolled: { beginner: 5, advanced: 4 },
    seats: 15,
    icon: Gamepad2,
    tutor: genericTutor,
  },
  {
    id: 'video-editing',
    title: 'Video Editing',
    titleBs: 'Video Editing',
    description: 'Learn editing, pacing, sound, transitions, and visual polish so raw footage becomes a clear, engaging, and professionally packaged video. The program covers both short-form and long-form formats, with a focus on storytelling, rhythm, and creator-ready final export.',
    descriptionBs: 'Nauči montažu, ritam, zvuk, tranzicije i vizuelnu obradu kako bi sirovi materijal postao jasan, zanimljiv i profesionalno upakovan video. Program pokriva i short-form i long-form formate, sa fokusom na storytelling, tempo i creator-ready finalni export.',
    schedule: 'Thu-Sat · Time coming soon',
    scheduleBs: 'Čet-Sub · Uskoro satnica',
    beginnerFocus: 'Cuts, timing, sound, transitions, and clean exports.',
    beginnerFocusBs: 'Rezovi, tempo, zvuk, tranzicije i čisti export.',
    advancedFocus: 'Story pacing, color, motion, and creator delivery pipelines.',
    advancedFocusBs: 'Story pacing, color, motion i creator delivery pipeline.',
    enrolled: { beginner: 4, advanced: 3 },
    seats: 15,
    icon: Video,
    tutor: genericTutor,
  },
];
