import {
  Bot,
  CarFront,
  Code2,
  Cuboid,
  Cpu,
  Gamepad2,
  Monitor,
  Palette,
  Printer,
  Smartphone,
  Sparkles,
  Trophy,
  Users,
  UtensilsCrossed,
  Video,
  SunMedium,
} from 'lucide-react';
import type {
  Amenity,
  MembershipDay,
  MembershipDayKey,
  MembershipSlot,
  MembershipSlotKey,
  Program,
} from './types';

export const membershipDays: MembershipDay[] = [
  { key: 'monday', label: 'Monday', labelBs: 'Ponedjeljak', shortLabel: 'MON', shortLabelBs: 'PON', summary: 'Fresh start', summaryBs: 'Novi start' },
  { key: 'tuesday', label: 'Tuesday', labelBs: 'Utorak', shortLabel: 'TUE', shortLabelBs: 'UTO', summary: 'Build mode', summaryBs: 'Build mode' },
  { key: 'wednesday', label: 'Wednesday', labelBs: 'Srijeda', shortLabel: 'WED', shortLabelBs: 'SRI', summary: 'Midweek focus', summaryBs: 'Sredina sedmice' },
  { key: 'thursday', label: 'Thursday', labelBs: 'Cetvrtak', shortLabel: 'THU', shortLabelBs: 'CET', summary: 'Creative flow', summaryBs: 'Kreativni flow' },
  { key: 'friday', label: 'Friday', labelBs: 'Petak', shortLabel: 'FRI', shortLabelBs: 'PET', summary: 'Launch energy', summaryBs: 'Launch energija' },
  { key: 'saturday', label: 'Saturday', labelBs: 'Subota', shortLabel: 'SAT', shortLabelBs: 'SUB', summary: 'Weekend lab', summaryBs: 'Vikend lab' },
  { key: 'sunday', label: 'Sunday', labelBs: 'Nedjelja', shortLabel: 'SUN', shortLabelBs: 'NED', summary: 'Closed', summaryBs: 'Zatvoreno', closed: true },
];

export const membershipSlots: MembershipSlot[] = [
  { key: 'slot1', label: '08:00 - 10:00' },
  { key: 'slot2', label: '10:00 - 12:00' },
  { key: 'slot3', label: '12:00 - 14:00' },
  { key: 'slot4', label: '14:00 - 16:00' },
];

export const slotOrder: Record<MembershipSlotKey, number> = {
  slot1: 0,
  slot2: 1,
  slot3: 2,
  slot4: 3,
};

export const createAvailability = (): Record<MembershipDayKey, Record<MembershipSlotKey, number>> => ({
  monday: { slot1: 9, slot2: 8, slot3: 7, slot4: 10 },
  tuesday: { slot1: 11, slot2: 6, slot3: 5, slot4: 9 },
  wednesday: { slot1: 7, slot2: 4, slot3: 6, slot4: 8 },
  thursday: { slot1: 10, slot2: 9, slot3: 6, slot4: 7 },
  friday: { slot1: 8, slot2: 5, slot3: 4, slot4: 6 },
  saturday: { slot1: 12, slot2: 10, slot3: 9, slot4: 11 },
  sunday: { slot1: 0, slot2: 0, slot3: 0, slot4: 0 },
});

export const amenities: Amenity[] = [
  {
    title: '15 AI Coding Stations + Chill Lounge',
    titleBs: '15 AI Coding Stanica + Chill Lounge',
    description: 'A 15-place AI-equipped coding zone paired with a chill lounge for breaks, gaming, and reset between work sessions.',
    descriptionBs: 'Zona sa 15 AI opremljenih coding mjesta i chill lounge dijelom za pauzu, gaming i reset između radnih sesija.',
    icon: Monitor,
  },
  {
    title: 'PlayStation 5',
    titleBs: 'PlayStation 5',
    description: 'Console zone for breaks, tournaments, and social hangouts between sessions.',
    descriptionBs: 'Konzola zona za pauze, turnire i druženje između sesija.',
    icon: Gamepad2,
  },
  {
    title: 'VR Corner',
    titleBs: 'VR Kutak',
    description: 'Immersive virtual reality experiences that make tech feel tangible and fun.',
    descriptionBs: 'VR iskustva koja čine tehnologiju opipljivom, modernom i zabavnom.',
    icon: Sparkles,
  },
  {
    title: 'Table Football',
    titleBs: 'Stoni Fudbal',
    description: 'Fast break energy for teams, rivals, and mid-session resets.',
    descriptionBs: 'Brza pauza za timove, rivale i reset između sesija.',
    icon: Trophy,
  },
  {
    title: '3D Printer + Free Filament',
    titleBs: '3D Printer + Besplatan Filament',
    description: 'Prototype ideas, parts, and school projects without extra material cost.',
    descriptionBs: 'Prototipi, dijelovi i školski projekti bez dodatnog troška materijala.',
    icon: Printer,
  },
  {
    title: 'Arduino + Robotics Kits',
    titleBs: 'Arduino + Robotika Kitovi',
    description: 'Hands-on electronics and robotics setup for sensors, movement, automation, and real prototype building.',
    descriptionBs: 'Praktična elektronika i robotika za senzore, kretanje, automatizaciju i izradu stvarnih prototipa.',
    icon: Cpu,
  },
  {
    title: 'Snacks',
    titleBs: 'Snack Zona',
    description: 'A casual fuel-up point to keep long creative blocks comfortable.',
    descriptionBs: 'Opuštena snack zona za lakše i udobnije kreativne blokove.',
    icon: UtensilsCrossed,
  },
  {
    title: 'Parking',
    titleBs: 'Parking',
    description: 'Reliable parking access for multiple vehicles, making drop-offs and longer stays easy.',
    descriptionBs: 'Stalan parking za više vozila, tako da su dolazak, ostanak i prevoz jednostavniji.',
    icon: CarFront,
  },
  {
    title: 'Rooftop Location',
    titleBs: 'Rooftop Lokacija',
    description: 'Set at the top of the building, with an open view, plenty of daylight, and a calm rooftop feel through the day.',
    descriptionBs: 'Smješten na vrhu zgrade, sa prelijepim pogledom, puno prirodnog svjetla i onim mirnim rooftop osjećajem kroz dan.',
    icon: SunMedium,
  },
];

export const programs: Program[] = [
  {
    id: 'web-dev',
    title: 'Web Dev',
    titleBs: 'Web Dev',
    description: 'Design and build modern websites, landing pages, and interactive interfaces.',
    descriptionBs: 'Dizajn i izrada modernih web stranica, landing pageova i interfejsa.',
    schedule: 'Mon + Wed · 17:00',
    scheduleBs: 'Pon + Sri · 17:00',
    beginnerFocus: 'HTML, CSS, JavaScript, responsive thinking.',
    beginnerFocusBs: 'HTML, CSS, JavaScript i responsive razmisljanje.',
    advancedFocus: 'React, APIs, deployment, and product polish.',
    advancedFocusBs: 'React, API integracije, deployment i product polish.',
    seats: 15,
    icon: Code2,
  },
  {
    id: 'app-dev',
    title: 'App Dev',
    titleBs: 'App Dev',
    description: 'Build mobile-first products and understand how ideas become real apps.',
    descriptionBs: 'Pravi mobilne proizvode i uci kako ideja postaje prava aplikacija.',
    schedule: 'Tue + Thu · 17:00',
    scheduleBs: 'Uto + Cet · 17:00',
    beginnerFocus: 'Mobile UX basics, app logic, prototyping, and publishing flow.',
    beginnerFocusBs: 'Osnove mobile UX-a, logika appova, prototip i publishing flow.',
    advancedFocus: 'React Native concepts, APIs, state, and app iteration.',
    advancedFocusBs: 'React Native koncepti, API-ji, state i iteracija aplikacije.',
    seats: 15,
    icon: Smartphone,
  },
  {
    id: 'ui-ux',
    title: 'UI/UX Graphic Design',
    titleBs: 'UI/UX Graphic Design',
    description: 'Shape interfaces, flows, colors, and visual systems that users enjoy.',
    descriptionBs: 'Oblikuj interfejse, flow, boje i vizuelne sisteme koje korisnici vole.',
    schedule: 'Tue + Fri · 17:00',
    scheduleBs: 'Uto + Pet · 17:00',
    beginnerFocus: 'Layout, typography, wireframes, and design habits.',
    beginnerFocusBs: 'Layout, tipografija, wireframe i dobre design navike.',
    advancedFocus: 'Design systems, product flows, and polished prototypes.',
    advancedFocusBs: 'Design sistemi, product flow i dotjerani prototipi.',
    seats: 15,
    icon: Palette,
  },
  {
    id: 'ai-program',
    title: 'AI Program',
    titleBs: 'AI Program',
    description: 'Learn how AI tools work and how to use them for real creative output.',
    descriptionBs: 'Nauci kako AI alati rade i kako ih koristiti za stvarne rezultate.',
    schedule: 'Wed + Fri · 17:00',
    scheduleBs: 'Sri + Pet · 17:00',
    beginnerFocus: 'Prompting, AI safety, practical automation, and workflows.',
    beginnerFocusBs: 'Prompting, AI sigurnost, automacija i korisni workflowi.',
    advancedFocus: 'Model strategy, product ideas, and advanced creator pipelines.',
    advancedFocusBs: 'Strategija modela, product ideje i napredni creator pipelineovi.',
    seats: 15,
    icon: Bot,
  },
  {
    id: '3d-modeling',
    title: '3D Modeling and 3D Print',
    titleBs: '3D Modeling and 3D Print',
    description: 'Move from digital object design to real-world printed output.',
    descriptionBs: 'Idi od digitalnog modela do pravog 3D printanog rezultata.',
    schedule: 'Mon + Thu · 17:00',
    scheduleBs: 'Pon + Cet · 17:00',
    beginnerFocus: 'Shapes, scale, printable models, and file preparation.',
    beginnerFocusBs: 'Oblici, skala, printable modeli i priprema fajlova.',
    advancedFocus: 'Functional parts, detailing, prototyping, and print optimization.',
    advancedFocusBs: 'Funkcionalni dijelovi, detalji, prototipi i optimizacija printa.',
    seats: 15,
    icon: Cuboid,
  },
  {
    id: 'arduino-robotics',
    title: 'Arduino and Robotics',
    titleBs: 'Arduino i Robotika',
    description: 'Build electronics, smart devices, and beginner robotics systems through hands-on projects.',
    descriptionBs: 'Pravi elektroniku, pametne uredjaje i pocetne robotske sisteme kroz prakticne projekte.',
    schedule: 'Mon + Fri Â· 17:00',
    scheduleBs: 'Pon + Pet Â· 17:00',
    beginnerFocus: 'Sensors, LEDs, circuits, Arduino basics, and simple robot movement.',
    beginnerFocusBs: 'Senzori, LED, strujna kola, Arduino osnove i jednostavno kretanje robota.',
    advancedFocus: 'Automation logic, multi-component builds, robotics control, and prototype integration.',
    advancedFocusBs: 'Automatizacija, slozeniji sklopovi, upravljanje robotikom i integracija prototipa.',
    seats: 15,
    icon: Cpu,
  },
  {
    id: 'game-dev',
    title: 'Game Dev',
    titleBs: 'Game Dev',
    description: 'Create game ideas, mechanics, worlds, and playful digital experiences.',
    descriptionBs: 'Kreiraj game ideje, mehanike, svjetove i zabavna digitalna iskustva.',
    schedule: 'Wed + Sat · 17:00',
    scheduleBs: 'Sri + Sub · 17:00',
    beginnerFocus: 'Game logic, level thinking, storytelling, and interaction basics.',
    beginnerFocusBs: 'Game logika, level thinking, storytelling i osnove interakcije.',
    advancedFocus: 'Production flow, systems, balancing, and playable demos.',
    advancedFocusBs: 'Production flow, sistemi, balans i playable demo verzije.',
    seats: 15,
    icon: Gamepad2,
  },
  {
    id: 'roblox-game-dev',
    title: 'Roblox Game Dev',
    titleBs: 'Roblox Game Dev',
    description: 'Build Roblox worlds, gameplay loops, and scripted multiplayer experiences.',
    descriptionBs: 'Pravi Roblox svjetove, gameplay loopove i scripted multiplayer iskustva.',
    schedule: 'Fri + Sat · 17:00',
    scheduleBs: 'Pet + Sub · 17:00',
    beginnerFocus: 'Roblox Studio basics, level building, gameplay logic, and simple Lua scripting.',
    beginnerFocusBs: 'Roblox Studio osnove, gradnja levela, gameplay logika i jednostavni Lua skriptovi.',
    advancedFocus: 'Lua systems, multiplayer mechanics, progression loops, and polished publish-ready projects.',
    advancedFocusBs: 'Lua sistemi, multiplayer mehanike, progression loopovi i dotjerani publish-ready projekti.',
    seats: 15,
    icon: Gamepad2,
  },
  {
    id: 'video-editing',
    title: 'Video Editing',
    titleBs: 'Video Editing',
    description: 'Cut, polish, and package short-form and long-form video projects.',
    descriptionBs: 'Montiraj, dotjeraj i pripremi short-form i long-form video projekte.',
    schedule: 'Thu + Sat · 17:00',
    scheduleBs: 'Cet + Sub · 17:00',
    beginnerFocus: 'Cuts, timing, sound, transitions, and clean exports.',
    beginnerFocusBs: 'Rezovi, tempo, zvuk, tranzicije i cisti export.',
    advancedFocus: 'Story pacing, color, motion, and creator delivery pipelines.',
    advancedFocusBs: 'Story pacing, color, motion i creator delivery pipeline.',
    seats: 15,
    icon: Video,
  },
];
